- .travis.yml
- appveyor.yml
- circle.yml
- scikit-ci.yml
$ git shortlog 0.10.0..0.11.0 --no-merges
Jean-Christophe Fillion-Robin (6):
docs/make_a_release: Re-order steps to account for use of versioneer
docs/make_a_release: Ensure uploaded distributions are signed
docs/make_a_release: Update reference to external documentation
docs/addons: Fix typo in enable-worker-remote-access section
addon/install_pyenv: Use PYTHON_VERSION instead of PYTHONVERSION
addon/install_pyenv: Skip brew update/upgrade if python if found in the cache
> ci: Improve MacOSX build time updating scikit-ci-addons

- scikit-ci.yml
This is workaround waiting scikit-build/scikit-build#247 is addressed.
See https://github.com/MacPython/wiki/wiki/Spinning-wheels#question-will-pip-give-me-a-broken-wheel
> travis: Ensure MacOSX wheels can be installed

- .circleci/config.yml
- .travis.yml
- appveyor.yml
- scikit-ci.yml
This commit also removes the use of $<RUN_ENV> command wrapper. Indeed,
scikit-build already takes care of setting up the expected environment
and installed requirements are either pure-python packages are already
distributed as wheels.
> ci: Automatically upload wheels to PyPi when publishing a tag

- CMakeUrls.cmake
- README.rst
- docs/index.rst
- tests/test_distribution.py
Note that Python supports macOS 10.9+, but CMake 3.16 currently only supports 10.12+. See https://gitlab.kitware.com/cmake/cmake/issues/20054 .
> Update to CMake 3.16.0

- docs/update_cmake_version.rst
This makes the commands easier to copy into non-bash shells, like fish, without breaking bash in the process.
> Drop `{}` syntax in update example

- CMakeUrls.cmake
- README.rst
- docs/index.rst
- tests/test_distribution.py
Update to 3.18.2. This version has several (at least three) important updates for FindPython, and would be very helpful to have for work on pybind11's packaging. Thanks, @jcfr!
> Update to CMake 3.18.2

- .travis.yml
> ci: Update travis to fix "libintl" loading error

- .travis.yml
- CMakeLists.txt
- appveyor.yml
- scikit-ci.yml
- scripts/manylinux2014-aarch64-build-and-install-openssl.sh
- scripts/manylinux2014-aarch64-build-and-test-wheel.sh
Fixes #115 
Build arm64 wheel on Travis CI in order to build natively, instead of cross compiling from x86_64. This fixes several problems with the Arm wheel. It makes use of `arch: arm64-graviton2`, which is currently only available on travis-ci.com. It is probably possible to build the project on travis-ci.org with `arch: arm64` instead, but it will be significantly slower.
See #115 for more information.
> ci: do arm64 builds natively on TravisCI

- .circleci/config.yml
- .travis.yml
- CMakeUrls.cmake
- README.rst
- docs/index.rst
- tests/test_distribution.py
- Update to CMake 3.18.4
- Remove redundant (and broken) aarch64 builds from CircleCI
- Switch to using Travis-CI Graviton 2 builder instances which are much faster
I'm creating this PR selfishly in order to bump the cmake version so new wheels can be released to Pypi.org. This will fix the currently broken aarch64 wheel that is published there.
> Update to CMake 3.18.4

- .travis.yml
<s>**Note:** Merge only after reverting `branch` associated with `deploy-master` from `fix-travis-arm64-release-deployment-step` to `master`</s>
---------------
* Remove setting of PYTHON_VERSION environment variable. This variable
had non effect and was set to an incorrect value. At the time of this
commit python version 3.8.2 was the default.
* Explicitly install twine when operating system is Linux
* Update deploy-release step to update PATH instead of explicitly referencing
the path to twine executable, this will allow the deployment to work on
both  macOS and Linux
* Update deploy-master step to display version of twine and catch potential
issue with deploy-release step.
> ci/travis: Attempt to fix pypi upload of arm64 wheel

- pyproject.toml
See #103
Co-authored-by: Yoav Alon <yoav@orca.security>
> Add pyproject.toml to specify build requirements for CMake wheels

- requirements-dev.txt
cryptography>=3.4 is only usable on manylinux2010+ systems becaus of the lack of a decent rust compiler on older systems.
Pin version of cryptography to 3.3.x on linux i686/x86_64.
Pre-requisite to #127
> fix: pin cryptography to a version working on manylinux1

- pyproject.toml
This will cause installing from source to succeed or provide a much better error with pip 10+.
See https://github.com/scikit-build/ninja-python-distributions/pull/26
> feat: download scikit-build when building from source

- CMakeUrls.cmake
- README.rst
- docs/index.rst
- docs/update_cmake_version.rst
- scripts/update_cmake_version.py
- tests/test_distribution.py
#114 has been updated and would be nice to include in 3.19.1's release, too. #117 looks safe to me, too.
> chore: update to cmake 3.19.1

- setup.py
This closes #126 by adding more links to the PyPI sidebar. Very minor other cleanup.
> docs: add project URLs

- setup.py
- tests/test_distribution.py
- versioneer.py
Same issues as were found in Ninja distribution https://github.com/scikit-build/ninja-python-distributions/pull/43 when building from sdist:
1. Add a test to build from sdist.
2. Use the same fixes the ones in  https://github.com/scikit-build/ninja-python-distributions/pull/43
2.1 The "import issue" affects all builds from sdist
2.2 The ill-specified version returned by versioneer only impacts ci as it would be impossible to upload the sdist to PyPI
> fix: building from sdist fails

- .circleci/config.yml
- .travis.yml
- appveyor.yml
- scikit-ci.yml
- scripts/convert_to_generic_platform_wheel.py
- setup.py
Main goal:
- Deploy a single py2.py3 wheel per platform: saves build time, space on PyPI & maybe bandwidth.
- Update `convert_to_generic_platform_wheel` to convert to a `py2.py3` wheel & update jobs not to have python 2.7 jobs
- Add a test only python 2.7 job not to introduce regressions for python 2
- Add a check that only 1 wheel per platform is built/uploaded
- fix: Only rely on auditwheel to add manylinux* platform tags
Other goals:
- Check the content of the list/* with twine  check on every commit
- This allowed to fix 2 issues:
1. The `long_description_content_type` was missing in the metadata
2. The deployment step on circle-ci would have failed on release
> Deploy a single py2.py3 wheel per platform

- .circleci/config.yml
> ci: fix CircleCI upload on tag issues

- .circleci/config.yml
- .travis.yml
- appveyor.yml
- scripts/manylinux2014-build-and-test-wheel.sh
The 0.17.5 version is causing issues in CI.
Given those issues will go away when moving to cibuildwheel, I'd rather pin to `<0.17.5` than investigate this some more.
> ci: pin `ruamel.yaml<0.17.5`

- .travis.yml
- MANIFEST.in
- appveyor.yml
- requirements-deploy.txt
- requirements-dev.txt
- requirements-repair.txt
- requirements-test.txt
- scikit-ci.yml
- scripts/manylinux2014-build-and-test-wheel.sh
- setup.py
Pre requisite to #139 to allow installing only what's really needed at a given step.
This works well enough but I'm clearly not a fan of this as-is. Any improvement suggestions are welcome.
> refactor: split requirements

- .github/workflows/build.yml
- CONTRIBUTING.rst
- docs/update_cmake_version.rst
- noxfile.py
- pyproject.toml
- setup.cfg
- setup.py
This removes `test_requires` and `setup_requires`, as they are deprecated. This also adds nox, making it easier for new contributors to get started, as well as simplifying some tasks. Bumping to the latest version can now be done with `nox -s bump`!
> chore: add nox and remove deprecated things

- .pre-commit-config.yaml
- scripts/convert_to_generic_platform_wheel.py
- scripts/update_cmake_version.py
- src/cmake/_version.py
- tests/__init__.py
- tests/test_cmake.py
- tests/test_distribution.py
- versioneer.py
Currently updating to 2.7+ syntax.
> chore: add pyupgrade

- .github/workflows/build.yml
- .travis.yml
use GHA to build aarch64, ppc64le & s390x wheels on tag
- also setup a scheduled run of the workflow to check aarch64, ppc64le & s390x builds
- allow manually dispatched workflow to check aarch64, ppc64le & s390x builds
partial fix to #159
> ci: use GHA to build aarch64, ppc64le & s390x wheels on tag

- .github/workflows/build.yml
- .travis.yml
- pyproject.toml
release notes: https://github.com/pypa/cibuildwheel/releases/tag/v2.0.0
> chore: update cibuildwheel from 2.0.0a4 to 2.0.0

- docs/make_a_release.rst
I don't actually do the first and last few items; there is no problem doing
this from any checkout (from GitHub Desktop or `gh`, for example), and CI
should be testing it, so we could strip those items for simplicity.
> docs: update release docs a bit

- CMakeLists.txt
When building from sources on Linux, libuv didn't respect `CMakePythonDistributions_ARCHIVE_DOWNLOAD_DIR` preventing building the sdist without an internet connection.
It is now respected allowing to build the sdist with:
```
SKBUILD_CONFIGURE_OPTIONS="-DCMakePythonDistributions_ARCHIVE_DOWNLOAD_DIR:PATH=$(pwd)/downloads" pip wheel -v cmake-3.21.1.tar.gz
```
assuming cmake & llibuv source archives are available in `$(pwd)/downloads`
fix #172
> fix: libuv now respect `CMakePythonDistributions_ARCHIVE_DOWNLOAD_DIR`

- .github/workflows/build.yml
- CMakeLists.txt
- pyproject.toml
CMake provides a much more recent libuv than we're currently building.
1.23.0 is the last version to build on CentOS 5
There's no reason to be stuck with this version when building from sdist or when building on manylinux2010+
Relying on the version embedded in CMake seems much safer than using this old version.
For now, the embedded version is used only when building on glibc>=2.12 to keep the same behavior on other UNIX flavors.
I guess we could maybe do the opposite and only use 1.23.0 when detecting glibc < 2.12 but otherwise always use the embedded one.
This also raises 1 question:
- should manylinux2010 wheels be built in addition to manylinux1 wheels ? (as I guess dropping manylinux1 is not an option here)
> chore: only use custom libuv for glibc<2.12

- .github/workflows/build.yml
- .travis.yml
- pyproject.toml
This adds musllinux wheel builds in CI workflows.
Still a draft while waiting for upstream cibuildwheel support
We can't use `pipx install -f --pip-args="-c {project}/constraints-ci.txt" cmake` on musllinux for now.
This would require installing openssl-dev as a pre-step.
With https://github.com/pypa/cibuildwheel/discussions/799, we could do either one of the following:
```toml
[[tool.cibuildwheel.overrides]]
build = "cp39-musllinux*"
before-all = [
"apk install openssl-dev",
"pipx install -f --pip-args=\"-c {project}/constraints-ci.txt\" cmake",
"cmake --version",
"pipx install -f --pip-args=\"-c {project}/constraints-ci.txt\" ninja",
"ninja --version",
"./scripts/manylinux-build-and-install-openssl.sh",
]
```
or using the pre-installed cmake in musllinux images:
```toml …
```
> feat: build musllinux_1_1 wheels

- scripts/manylinux-build-and-install-openssl.sh
The OpenSSL 1.1.1 series is still supported until 11th September 2023.
Maybe we should wait to upgrade to the 3.0 series ? Maybe not ?
> chore: update to OpenSSL 3.0.0

- .github/workflows/build.yml
there's a race condition in the workflow that allows test_sdist tests to run with wheels present in the dist folder which will fail.
> fix(ci): do no run tests on wheel in sdist tests

- pyproject.toml
Tests are too long for QEMU based builds and some are failing because running with QEMU.
Just disable them for now.
c.f. https://github.com/scikit-build/cmake-python-distributions/actions/runs/1940654996
> chore: disable CMake tests on alt-archs

- scripts/manylinux-build-and-install-openssl.sh
> chore: bump OpenSSL 3.0.1 → 3.0.3

- noxfile.py
- scripts/manylinux-build-and-install-openssl.sh
- scripts/update_openssl_version.py
Add helper script and nox session to bump openssl.
Similar to what's being done to bump cmake.
Used to create #243
> chore: add script to bump OpenSSL version

- .github/workflows/build.yml
- CMakeLists.txt
- CMakeUrls.cmake
- README.rst
- docs/index.rst
- docs/update_cmake_version.rst
- setup.py
- tests/test_distribution.py
- Update to cmake 3.23.3
- Drop manylinux1 wheels
cmake >= 3.23 requires a version of libuv that can't be built on manylinux1.
This drops manylinux1 wheels in favor of manylinux2010 wheels.
> Update to cmake 3.23.3

- setup.py
with `include_package_data=True` setuptools include a bunch of files that shouldn't be present in the wheel.
fix #277
> fix: only include `py.typed` package_data

- src/cmake/__init__.py
This make it harder to mock system calls because platform calls `uname`. Using `sys.platform.startswith` is the canonical way to do this anyway.
> fix: avoiding an extra system call

- scripts/manylinux-build-and-install-openssl.sh
This reverts commit 303723902e209f3ac15f01bd5e1adeb7ffed368f.
Per https://www.openssl.org:
> 12-Oct-2022 OpenSSL 3.0.6 and 1.1.1r are withdrawn. New releases will be created in due course.
> Revert "Update to OpenSSL 3.0.6 (#294)"

- src/cmake/__init__.py
Fixes #290. Broken for us since Python 3.2.
> fix: don't close all file descriptors

- CMakeLists.txt
- src/cmake/__init__.py
This commit unbundles the macOS app to keep only what's really needed & get rid of the GUI stuff.
fix #301
> fix: Application bundle integrity issues on macOS 13

- pyproject.toml
This reverts commit 7e5ba4b9f6591f58bf59706efda15e284e4194e3.
scikit-build 0.16 has been yanked so the check should not be required anymore.
The `git config --global protocol.file.allow always` does not work in #300  and might be dangerous if doing local builds with cibuildwheels. The CMake test suite will be fixed in 3.24.3 / 3.25.0.
> Revert "ci: fix issue with git security fix (#302)"

- .pre-commit-config.yaml
- docs/conf.py
- pyproject.toml
- scripts/convert_to_generic_platform_wheel.py
- scripts/repair_wheel.py
- scripts/update_cmake_version.py
- setup.cfg
- setup.py
- src/cmake/__init__.pyi
- tests/test_cmake.py
Should stop pre-commit from trying to upgrade pyupgrade!
> chore: switch to ruff

- requirements-deploy.txt
- requirements-dev.txt
- requirements-test.txt
This will get rid of the security alerts.
> chore: remove unused `requirements-deploy.txt`

- noxfile.py
This prevents bumping to 3.1.x which is not a LTS version.
> chore: only bump OpenSSL to 3.0.x (current LTS version)

- .github/workflows/build.yml
> chore: use trusted publisher deployment

- CMakeUrls.cmake
- README.rst
- docs/index.rst
- docs/update_cmake_version.rst
- tests/test_distribution.py
> Update to CMake 3.27.1

- .github/workflows/build.yml
Hopefully supporting actions/artifact@v2. See https://github.com/pypa/cibuildwheel/issues/1699, using fix there and in https://github.com/scientific-python/cookie/pull/335. There's an issue asking for guidance here: https://github.com/actions/upload-artifact/issues/472.
> ci: support artifact v4

- CMakeLists.txt
- pyproject.toml
Linux runners now come with 4 threads.
> chore(ci): use 4 threads to compile on GHA

- .github/workflows/build.yml
- docs/conf.py
- docs/index.rst
- docs/make_a_release.rst
- scripts/utils.sh
> chore: move to main

- CMakeLists.txt
- CMakeUrls.cmake
- README.rst
- docs/index.rst
- docs/update_cmake_version.rst
- pyproject.toml
- tests/test_cmake.py
I've also pushed a final py2 release with scikit-build classic of 3.28.4 with Python 2 support fixed (it's been broken for quite a while, at least accessing it from Python has).
> Update to CMake 3.29.0

- pyproject.toml
- src/cmake/__init__.py
- tests/test_cmake.py
Fixes a regression introduced in 5f068d5 ("chore(build): move to scikitbuild-core (#455)", 2024-03-01)
> fix: Ensure importlib_metadata runtime dependency installed with Python < 3.10

- docs/conf.py
- pyproject.toml
- scripts/update_cmake_version.py
- scripts/update_openssl_version.py
- tests/__init__.py
- tests/test_cmake.py
More checks, pulled from #470.
> chore: update ruff config

- CMakeLists.txt
- pyproject.toml
Some updates mostly pulled from #470.
> chore: update cibuildwheel config

- .pre-commit-config.yaml
- noxfile.py
- pyproject.toml
- scripts/update_cmake_version.py
- scripts/update_openssl_version.py
This fixes the instruction printout to include `pyproject.toml` - and modernizes the whole script.
> chore: modernize update scripts

- .readthedocs.yaml
- docs/make_a_release.rst
> docs: fix rtd and update release instructions

- pyproject.toml
Hoping this can be fixed in cibuildwheel, but for now, overrides don't work.
See https://github.com/pypa/cibuildwheel/issues/1803.
> ci: fix test disabling

- pyproject.toml
Fixes #489 
It looks like the dependency on `importlib_metadata` was accidentally removed in https://github.com/scikit-build/cmake-python-distributions/pull/470.
This PR adds it back.
> Add back the dependency on importlib_metadata for python < 3.8

- pyproject.toml
With the cibuildwheel update, `musllinux_1_2` is the default.
This gets `musllinux_1_1` wheels back.
> fix: use musllinux_1_1 images

- pyproject.toml
with setuptools_scm gone, I forgot to bump the version before tagging. Bump the version to 3.29.5.1, the tag will be overriden once this gets merged.
> bump version to 3.29.5.1

- README.rst
Follow-up of 56fc87990 (README: Update download stats [ci skip]) switching to using "pepy.tech" badge instead of hard-coded total download count expected to be manually retrieved using Google's BigQuery.
See https://pypistats.org/faqs#what-is-the-source-of-the-download-data
> doc(README): Use up-to-date download stats badge

- .github/workflows/build.yml
python 3.7 is not available on ubuntu-latest runner & latest uv fails to create a venv on ubuntu-22.04.
> fix(ci): use python 3.8 instead of python 3.7 to check sdist

- src/cmake/__init__.py
Similar to pipx. Keeps the Python process from having around, and lets you interact directly with the new process.
> fix: replace process on UNIX

- docs/build_system.rst
- docs/conf.py
- docs/requirements.txt
See https://github.com/blockdiag/blockdiag/pull/171.
Used ChatGPT to convert to mermaid and build the description table.
> docs: move off of abandoned dep

- CMakeLists.txt
- pyproject.toml
- src/cmake/__init__.py
See https://github.com/scikit-build/cmake-python-distributions/issues/66
> Add support for distributing ccmake executable

- src/cmake/__init__.py
Fix #557.
This can only be seen if there's a CMakeLists.txt in the directory, which is why my local `--version` checks were passing.
> fix: make sure the full path is visible to the program too

- .github/workflows/build.yml
- README.rst
- scripts/manylinux-build-and-install-openssl.sh
mitigates #494
PS: armv7l (both musllinux & manylinux) are building ninja from sources for now. ref https://github.com/scikit-build/ninja-python-distributions/issues/271
> feat: add manylinux_2_31 armv7l wheel

- tests/test_cmake.py
Now that process gets replaced on UNIX, tests were not running (pytest got replaced with the first script invocation and returned success).
> fix: tests

- CMakeLists.txt
Since 3.24.0, CMake requires CMake 3.13+ to build itself, scikit-build-core requires 3.15+
Align the version in CMakeLists.txt with the one of scikit-build-core.
This also gets rid of a warning.
> chore: align minimum cmake version with the one of scikit-build-core

- .github/workflows/build.yml
- _build_backend/backend.py
- pyproject.toml
This PR declares a custom build backend for the CMake PyPI distrbution. The following are included:
- removes the Ninja PyPI distribution build dependency by default in order to break a build cycle (cmake -> ninja -> cmake) when binary wheels are not available and Ninja is not present/too old on the build system. (this is #566)
- removes the CMake PyPI distrbution build dependency by default in order to break a build cycle (cmake -> cmake) when binary wheels are not available and CMake is not present/too old on the build system.
- Uses a bootstrapped CMake in order to build itself when CMake is not present/too old on the build system.
Relates to https://github.com/scikit-build/cmake-python-distributions/issues/503#issuecomment-2191858783.
The bootstrap build might not be efficient as …
> fix: bootstrap build

- scripts/update_openssl_version.py
OpenSSL changed the format of the sha256 file in its releases.
Let's allow both format: `{sha256}` or `{sha256} {filename}`
> fix: sha256 in update script for OpenSSL

- .gitignore
- .pre-commit-config.yaml
- .readthedocs.yaml
- docs/requirements.txt
- noxfile.py
- pyproject.toml
Better noxfile, using latest features, too.
> chore: use dependency-groups

- pyproject.toml
It's the same as the global musllinux one
> chore: remove cibuildwheel override for musllinux_armv7l
