scikit-build/cmake-python-distributions

CMakeUrls.cmake
README.rst
docs/index.rst
tests/test_wheel.py

Update to CMake v3.9.0

---

CMakeUrls.cmake
README.rst
docs/index.rst
scikit-ci.yml
tests/test_wheel.py

I run `python scripts/update_cmake_version.py 3.11.0`

Update to cmake 3.11.0

---

CMakeUrls.cmake
docs/update_cmake_version.rst
scripts/update_cmake_version.py

Converts over `update_cmake_version` to query github, and runs the script to update the repo

Convert over to GitHub

---

.circleci/config.yml
.travis.yml
CMakeLists.txt
CMakeUrls.cmake
README.rst
appveyor.yml
cmake/__init__.py
docs/index.rst
requirements-dev.txt
scikit-ci.yml
tests/test_distribution.py

update to CMake 3.14.3 following instructions [here](https://cmake-python-distributions.readthedocs.io/en/latest/update_cmake_version.html).

update to CMake 3.14.3

---

.circleci/config.yml
.travis.yml
appveyor.yml
requirements-dev.txt
scikit-ci.yml
scripts/convert_to_generic_platform_wheel.py

Update CI configuration to only build one wheel for each Python
version.

Convert to generic platform wheel. See #71

---

CMakeUrls.cmake
README.rst
docs/index.rst
scikit-ci.yml
tests/test_distribution.py

This should hopefully be a start for updating to 3.15.

Update to CMake 3.15.3

---

.travis.yml
scikit-ci.yml
scripts/ssl-check.py

See https://github.com/scikit-build/cmake-python-distributions/issues/84

Fix SSL import when using pip or twine on Travis

---

CMakeUrls.cmake
README.rst
docs/index.rst
tests/test_distribution.py

Note that 3.16.0 has not been released to PyPI yet.

Update to CMake 3.16.3

---

scripts/manylinux2014-aarch64-build-and-install-openssl.sh

changelog: https://www.openssl.org/news/changelog.html#openssl-111
Builds on top of #128

chore: update OpenSSL 1.1.1h → 1.1.1k

---

.circleci/config.yml
.travis.yml
appveyor.yml
scripts/manylinux2014-build-and-test-wheel.sh

This reverts commit f03c50f54227330eb3e4be819086777cd7ec1a05.
Let's try with 0.17.6

Revert "ci: pin `ruamel.yaml<0.17.5` (#150)"

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
scripts/update_cmake_version.py
tests/test_distribution.py

Updated the script a bit, applied black. Now it updates the docs page too. I ran black on the helper script because flake8 complained in CI and I didn't want to fight it. :)

Update to CMake 3.20.3

---

.circleci/config.yml

This seems to time out fairly often. This might help.

ci: longer CircleCI timeout

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.20.4

---

.github/workflows/build.yml
.pre-commit-config.yaml
README.rst
docs/conf.py
docs/update_cmake_version.rst
noxfile.py
pyproject.toml
scripts/convert_to_generic_platform_wheel.py
scripts/repair_wheel.py
scripts/update_cmake_version.py
setup.cfg
setup.py
src/cmake/__init__.py
src/cmake/_version.py
tests/__init__.py
tests/test_cmake.py
tests/test_distribution.py
versioneer.py

- style: use pre-commit more places
- style: add Python 2 encoding pragmas
- style: fixed sorting

style: improve linting

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
noxfile.py
tests/test_distribution.py

update to cmake 3.20.5

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.21.0

---

constraints-ci.txt

this should probably be done by dependabot in the future.

chore(ci): update cmake & ninja

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.21.1

---

setup.py

fix: non-isolated build fails when versioneer is installed

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.21.2

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.21.3

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.22.0

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.22.1

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.22.2

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.22.3

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.22.4

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.22.5

---

scripts/manylinux-build-and-install-openssl.sh

Update to OpenSSL 3.0.4

---

scripts/manylinux-build-and-install-openssl.sh

Update to OpenSSL 3.0.5

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.22.6

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.24.0

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.24.1

---

setup.py

Signed-off-by: Henry Schreiner <henryschreineriii@gmail.com>

fix: typed files missing

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.24.2

---

scripts/manylinux-build-and-install-openssl.sh

Update to OpenSSL 3.0.6

---

pyproject.toml

ci: fix issue with git security fix

---

.github/workflows/build.yml

We are getting warnings about things like node 12 being removed soon.

chore(deps): GHA updates

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.24.3

---

scripts/manylinux-build-and-install-openssl.sh

Update to OpenSSL 3.0.7

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.25.0

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

update to cmake 3.25.2

---

scripts/manylinux-build-and-install-openssl.sh

Update to OpenSSL 3.0.8

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.26.0

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.26.1

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.26.3

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.26.4

---

scripts/manylinux-build-and-install-openssl.sh

Update to OpenSSL 3.0.9

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.27.0

---

scripts/manylinux-build-and-install-openssl.sh

Update to OpenSSL 3.0.10

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.27.2

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.27.4

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.27.5

---

scripts/manylinux-build-and-install-openssl.sh

Update to OpenSSL 3.0.11

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.27.6

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_distribution.py

Update to CMake 3.27.7

---

scripts/manylinux-build-and-install-openssl.sh

Update to OpenSSL 3.0.12

---

setup.py

The issue link might not be the best one ?
Related issues:
- #192
- #325 (applies to multiple comments, not the initial issue which is about Windows)
- #384 
- #386
- #392

doc: add a note about piwheels in the debug message

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_cmake.py

Update to CMake 3.28.0

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_cmake.py

Update to CMake 3.28.1

---

scripts/manylinux-build-and-install-openssl.sh

Update to OpenSSL 3.0.13

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
tests/test_cmake.py

Update to CMake 3.28.3

---

.github/workflows/build.yml
.readthedocs.yaml
CONTRIBUTING.rst
HISTORY.rst
README.rst
docs/build_system.rst
docs/building.rst
docs/conf.py
docs/index.rst
docs/make.bat
docs/make_a_release.rst
docs/requirements-docs.txt
noxfile.py
pyproject.toml

Adding read the docs file, fixing up linkcheck issues.

docs: fix up docs

---

.github/workflows/build.yml
.pre-commit-config.yaml
noxfile.py
pyproject.toml
scripts/update_cmake_version.py
scripts/update_openssl_version.py
src/cmake/__init__.py
tests/test_cmake.py

feat: drop <3.7

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
pyproject.toml
tests/test_cmake.py

Update to CMake 3.29.2

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
pyproject.toml
tests/test_cmake.py

Update to CMake 3.29.3

---

scripts/manylinux-build-and-install-openssl.sh

Update to OpenSSL 3.0.14

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
pyproject.toml
tests/test_cmake.py

Update to CMake 3.29.5

---

CMakeUrls.cmake
README.rst
docs/index.rst
docs/update_cmake_version.rst
noxfile.py
pyproject.toml
tests/test_cmake.py

update to cmake 3.29.6

---

README.rst

In addition of the total download, provide an idea of the relative current usage by also report the monthly download stats.
_Follow-up of comment from @henryiii in https://github.com/scikit-build/cmake-python-distributions/pull/532#issuecomment-2291665915_

doc(README): Add monthly download stats badge

---

.github/workflows/build.yml

This should silence a bunch of warnings in CI.

chore(ci): use `astral-sh/setup-uv` & `uv pip install --group`

---

CMakeLists.txt

fix: use version range and don't error of no macOS version is set
